### PR TITLE
update docs & ci config for latest docker engine

### PR DESCRIPTION
**Pull request by codevbus**
Adds compatibility with newer Docker and Docker Compose pattern.

### CODE REVIEW

**Comment by codevbus** [comment]
References #38

**Comment by asi-cider** [comment]
Thanks for the contribution! @codevbus 

1. Did you check if it's already installed on the CIrcleCI Ubuntu machine? We would like to save the time it takes to install this.
2. I saw here https://docs.docker.com/compose/install/ that it comes built-in in most installation scenarios. Maybe it would be better to prompt the users to first check if it's available and then show them the download instructions?
3. In order to get the CI to run you need to have a CIrcleCI account connected to your GitHub and then click "Set up project" on your fork inside CircleCI's webpage.

**Comment by codevbus** [comment]
@asi-cider - Thanks for taking a look!

I'll get CircleCI set up; that should give me some feedback on the changes.

Re: manual Docker installation: You are correct, it does look like the included package for `20.04` is current: https://packages.ubuntu.com/search?keywords=docker&searchon=names&suite=focal&section=all, however the packaged Docker Compose is still `~1` and might need manual installation(if they're not using Docker Desktop).

I'll update the instructions to distinguish between users who have the latest Docker Desktop versus users who might want to install on a fresh server instance.

**Comment by codevbus** [comment]
@asi-cider - Hello! Apologies for the delay.

I got circleCI running, but am encountering this error:

https://app.circleci.com/pipelines/github/codevbus/cicd-goat/4/workflows/0303c20d-b070-4c1a-a212-77c5755717e5/jobs/4?invite=true#step-105-8899

Are you seeing this upstream? Do you want me to fix it?

**Comment by TupleType** [comment]
Hey @codevbus!

Yea I fixed this few days ago, you can merge the main branch into yours to fix this

**Comment by asi-cider** [comment]
Hey @codevbus,

I fixed this few days ago, you can merge the main branch into yours and it'll solve this

Thanks!

**Comment by asi-cider** [comment]
@codevbus 
I've checked a newer image and ubuntu-2204:2022.07.1 has the compose command installed. 
About the download section, why did you replace --create-dirs to mkdir?

**Comment by codevbus** [comment]
@asi-cider 

> ubuntu-2204:2022.07.

Looks like the newer image has a newer python version than some of the constraints are expecting: https://circleci.com/api/v1.1/project/github/codevbus/cicd-goat/8/output/107/0?file=true&allocation-id=632156e84de91b2678cc507c-0-build%2F2ANITVV4

For the steps, I was getting inconsistent behavior running the commands all at once, I figured an explicit step was better. Can definitely change it back.

Should I go back to the previous image version with the explicit plugin install?

**Comment by asi-cider** [comment]
@codevbus 
Sorry for the late response.
You can update the python version requirement of the pipfiles and lets see maybe it'll work with the new image

**Review by asi-cider — APPROVED** [review]

**Pull request merged**
